### ISSUE TITLE
Tuya Device is discovered, but not coming online

### ISSUE THREAD

**Issue by Linzm99** [smarthomej/addons#366]
Hi
I used your Tuya binding and my project did come online and the discovery also finds my airconditioner and its channels. The problem is that the device isnt coming online. I can see the offline indicator flickering every few seconds. I guess this happens when the device broadcasts its IP address. Any idea why this isnt working? How can I debug this issue properly?

Thanks in advance!

**Comment by BigGeorgeTx** [comment]
In troubleshootinng devices, I found it helpful to check the version (3.1 vs 3.3).  I had a few that were 3.1 and they didn't come online until I switched them to 3.1.  Also with some I had to manually enter the IP address.  (I'm not a developer, just another user who has made good use of this binding).

**Comment by J-N-K** [comment]
I would suggest you set the log level to trace and show what is send and received to the device. And please let me know what the productId of the device is.

**Comment by owl770** [comment]
This is very similar to #358 - the issue is happening again (daily). I manage to get the tuyaDevice ```Thing``` to go online (by disabling it in OH and leaving it that way for many hours and then re-enabling it). It stays online and works normally until about 08:53AM (+/- a few minutes). FYI - I am located in the Australia/Sydney timezone.

My tuyaDevice ```Thing``` was discovered automatically and is configured as follows:
```
UID: tuya:tuyaDevice:81446666c82b96cac30d
label: Pool pumps
thingTypeUID: tuya:tuyaDevice
configuration:
  protocol: "3.3"
  productId: 3yj6z55c052okmi5
  deviceId: 81446666xxxxxxxac30d (partially redacted)
  localKey: xxxxxxxxxxxxxxxx (redacted)
channels:
  - id: switch_1
    channelTypeUID: tuya:switch
    label: switch_1
    description: null
    configuration:
      dp: 1
  - id: countdown_1
    channelTypeUID: tuya:number
    label: countdown_1
    description: null
    configuration:
      dp: 9
      max: 86400
      min: 0
```
I am running version ```3.2.12``` of the tuya binding on ```openhabian 3.2.0```.

Something to note is that in this environment, internet access is disabled at 23:00 and re-enabled at 07:00. There are also other smart switches in the environment that are not yet incorporated into the openHAB environment (the intention is that once I get the first one working reliably, I will add the rest). As of today, I have changed the settings so that the internet is on 24/7 to see if that has a positive effect.

Things to note from the event log (shown below) are:

- The tuya **project** ```changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)``` at ```2022-05-19 00:54:44.433``` - after the internet goes off at 23:00 the day before
- The tuya **project** ```changed from OFFLINE (COMMUNICATION_ERROR) to ONLINE``` at ```2022-05-19 07:02:04.934``` - after the internet comes back on at 07:00
- The tuya **thing** ```changed from ONLINE to UNKNOWN``` at ```2022-05-19 08:53:33.131```
- The tuya **thing** then cycles between ```OFFLINE-ONLINE-OFFLINE``` every 5 seconds


My latest event log with TRACE level logging is: [https://www.dropbox.com/s/m0w1wr0sv90lddw/events-trimmed.log?dl=0](url)

My latest openHAB log is: [https://www.dropbox.com/s/hmg5n8lfxzjwwcl/openhab-trimmed.log?dl=0](url)

Not sure if this is useful, but this is the two logs combined in chronological order: [https://www.dropbox.com/s/sqf7vii8hos0qnn/combined-trimmed.log?dl=0](url)

Once the tuyaDevice is ```ONLINE``` and stays ```ONLINE```, it works as expected.

Any assistance is greatly appreciated. If you need more diagnostics, please let me know because it seems quite reproducible (every 24 hours).
