### ISSUE TITLE
DP 17 add_ele updates not being received

### ISSUE THREAD

**Issue by tglanfield** [smarthomej/addons#534]
I'm not receiving regular DP 17 add_ele from my Tuya devices.  I can see the updates on Tuya IoT site so know the device is working. I'm receiving the other DP IDs on a regular basis.

Log file deleting and reconfiguring one of my devices.
https://pastebin.com/2AiGZWr3

I can provoke an update of all DPs by changing the interval:
https://pastebin.com/Fg10W6jg

I'm running OpenHAB 4.0.4.

```
openhab> bundle:list | grep Smart
bundle:list | grep Smart
247 │ Resolved │  80 │ 4.0.0                  │ SmartHome/J Add-ons :: Bundles :: Tuya Binding
248 │ Resolved │  80 │ 4.0.0                  │ SmartHome/J Add-ons :: Bundles :: Common Components
323 │ Active   │  80 │ 4.0.1                  │ SmartHome/J Add-ons :: Bundles :: Tuya Binding
324 │ Active   │  80 │ 4.0.1                  │ SmartHome/J Add-ons :: Bundles :: Common Components
```

```
UID: tuya:tuyaDevice:bf75ebe95676c927d3cxal
label: Mains Trip 1 - Downstairs Lights
thingTypeUID: tuya:tuyaDevice
configuration:
  pollingInterval: 0
  productId: cipuwutzfuqk3iru
  deviceId: bf75ebe95676c927d3cxal
  localKey: -_/H0hBen+}7Levb
channels:
  - id: light_mode
    channelTypeUID: tuya:string
    label: light_mode
    description: null
    configuration:
      dp: 40
      range: relay,pos,none,on
  - id: cur_voltage
    channelTypeUID: tuya:number
    label: cur_voltage
    description: null
    configuration:
      dp: 20
      max: 5000
      min: 0
  - id: cur_power
    channelTypeUID: tuya:number
    label: cur_power
    description: null
    configuration:
      dp: 19
      max: 34500
      min: 0
  - id: test_bit
    channelTypeUID: tuya:number
    label: test_bit
    description: null
    configuration:
      dp: 21
      max: 5
      min: 0
  - id: electric_coe
    channelTypeUID: tuya:number
    label: electric_coe
    description: null
    configuration:
      dp: 23
      max: 1000000
      min: 0
  - id: relay_status
    channelTypeUID: tuya:string
    label: relay_status
    description: null
    configuration:
      dp: 38
      range: power_off,power_on,last
  - id: cur_current
    channelTypeUID: tuya:number
    label: cur_current
    description: null
    configuration:
      dp: 18
      max: 100000
      min: 0
  - id: temp_value
    channelTypeUID: tuya:dimmer
    label: temp_value
    description: null
    configuration:
      dp: 47
      max: 999
      min: 0
  - id: add_ele
    channelTypeUID: tuya:number
    label: add_ele
    description: null
    configuration:
      dp: 17
      max: 50000
      min: 0
  - id: switch
    channelTypeUID: tuya:switch
    label: switch
    description: null
    configuration:
      dp: 1
  - id: electricity_coe
    channelTypeUID: tuya:number
    label: electricity_coe
    description: null
    configuration:
      dp: 25
      max: 1000000
      min: 0
  - id: power_coe
    channelTypeUID: tuya:number
    label: power_coe
    description: null
    configuration:
      dp: 24
      max: 1000000
      min: 0
  - id: voltage_coe
    channelTypeUID: tuya:number
    label: voltage_coe
    description: null
    configuration:
      dp: 22
      max: 1000000
      min: 0
  - id: countdown_1
    channelTypeUID: tuya:number
    label: countdown_1
    description: null
    configuration:
      dp: 9
      max: 86400
      min: 0
​
```
